#!/usr/bin/env python3
"""
Generator for src/chacha_ia16.S -- the ChaCha20 block function in 8086
assembly, used by libtomcrypt's chacha_crypt.c on ia16.

    python3 src/chacha_ia16.py > src/chacha_ia16.S

The generated file is committed so the ELKS build needs no Python.

    void chacha_block_ia16(unsigned char out[64], const ulong32 in[16]);

computes out = LE(ChaCha20 core with 20 rounds applied to in) + in, the
same as libtomcrypt's _chacha_block(out, in, 20).

Register plan for one quarter-round QR(a, b, c, d), 32-bit words as
hi:lo pairs of 16-bit registers:
  a in DI:SI, b in a pair of AX/BX, d in a pair of CX/DX (byte-addressable,
  for the rotate-by-8 byte swaps), c stays in memory.  BP points at the
  working copy x[16] on the stack.

Rotations (all branch-free, so timing doesn't depend on the data):
  <<<16  free: the generator swaps which register holds the high half
  <<<8   three byte xchgs
  <<<12  <<<8, then four 1-bit left rotates   (shl lo; rcl hi; adc lo,0)
  <<<7   <<<8, then one 1-bit right rotate    (ror lo; rcr hi; rcl lo; ror lo)

One double round (8 quarter-rounds) is unrolled; it runs 10 times.

Calling convention (ia16-elf-gcc, -mcmodel=medium): far call, cdecl, args
at [sp+4..] after the far return address, caller pops, callee preserves
SI, DI, BP; SS == DS.
"""

import sys

BYTE = {'ax': ('ah', 'al'), 'bx': ('bh', 'bl'), 'cx': ('ch', 'cl'), 'dx': ('dh', 'dl')}

out = []


def e(s):
    out.append('\t' + s + '\n')


def x(i, half):
    """Memory operand for half (0 = low word, 1 = high word) of x[i]."""
    off = 4 * i + 2 * half
    return 'word ptr [bp+%d]' % off if off else 'word ptr [bp]'


def rot8(p):
    lo, hi = p
    hh, hl = BYTE[hi]
    lh, ll = BYTE[lo]
    e('xchg\t%s, %s' % (hh, hl))
    e('xchg\t%s, %s' % (lh, ll))
    e('xchg\t%s, %s' % (hl, ll))


def rol1(p):
    lo, hi = p
    e('shl\t%s, 1' % lo)
    e('rcl\t%s, 1' % hi)
    e('adc\t%s, 0' % lo)


def ror1(p):
    lo, hi = p
    e('ror\t%s, 1' % lo)
    e('rcr\t%s, 1' % hi)
    e('rcl\t%s, 1' % lo)
    e('ror\t%s, 1' % lo)


def quarter_round(a, b, c, d):
    e('/* QR(%d, %d, %d, %d) */' % (a, b, c, d))
    A = ('si', 'di')
    B = ['ax', 'bx']   # [lo, hi]
    D = ['cx', 'dx']
    e('mov\tsi, %s' % x(a, 0))
    e('mov\tdi, %s' % x(a, 1))
    e('mov\tax, %s' % x(b, 0))
    e('mov\tbx, %s' % x(b, 1))
    e('mov\tcx, %s' % x(d, 0))
    e('mov\tdx, %s' % x(d, 1))
    # a += b; d ^= a; d <<<= 16
    e('add\tsi, %s' % B[0]); e('adc\tdi, %s' % B[1])
    e('xor\t%s, si' % D[0]); e('xor\t%s, di' % D[1])
    D.reverse()
    # c += d; b ^= c; b <<<= 12
    e('add\t%s, %s' % (x(c, 0), D[0])); e('adc\t%s, %s' % (x(c, 1), D[1]))
    e('xor\t%s, %s' % (B[0], x(c, 0))); e('xor\t%s, %s' % (B[1], x(c, 1)))
    rot8(B)
    for _ in range(4):
        rol1(B)
    # a += b; d ^= a; d <<<= 8
    e('add\tsi, %s' % B[0]); e('adc\tdi, %s' % B[1])
    e('xor\t%s, si' % D[0]); e('xor\t%s, di' % D[1])
    rot8(D)
    # c += d; b ^= c; b <<<= 7
    e('add\t%s, %s' % (x(c, 0), D[0])); e('adc\t%s, %s' % (x(c, 1), D[1]))
    e('xor\t%s, %s' % (B[0], x(c, 0))); e('xor\t%s, %s' % (B[1], x(c, 1)))
    rot8(B)
    ror1(B)
    # store a, b, d
    e('mov\t%s, si' % x(a, 0)); e('mov\t%s, di' % x(a, 1))
    e('mov\t%s, %s' % (x(b, 0), B[0])); e('mov\t%s, %s' % (x(b, 1), B[1]))
    e('mov\t%s, %s' % (x(d, 0), D[0])); e('mov\t%s, %s' % (x(d, 1), D[1]))


def main():
    out.append('''\
/*
 * chacha_ia16.S -- ChaCha20 block function for 8086/8088.
 *
 * GENERATED by src/chacha_ia16.py -- edit that, not this.
 *
 *   void chacha_block_ia16(unsigned char out[64], const ulong32 in[16]);
 *
 * out = LE(core20(in) + in), as libtomcrypt's _chacha_block(out, in, 20).
 * out and in must not overlap.
 */

	.arch	i8086
	.code16
	.intel_syntax noprefix

	/* The trailing $ is required by ELKS's medium-model linker script
	 * (see src/fe25519_ia16.py).  The character before it chooses the
	 * code segment: 0/2/4/6 near, anything else far.  'x' puts this in
	 * the far segment, since ssh's near segment is nearly full. */
	.section .fartext.chacha_ia16x$,"ax",@progbits

	.global	chacha_block_ia16
	.type	chacha_block_ia16, @function
chacha_block_ia16:
	push	si
	push	di
	push	bp
	sub	sp, 66			/* x[16] + round counter */
	mov	bp, sp
	/* args: out at [bp+66+6+4], in at [bp+66+6+6] */
	mov	si, [bp+78]		/* in */
''')
    for i in range(32):
        e('mov\tax, [si+%d]' % (2 * i) if i else 'mov\tax, [si]')
        e('mov\t%s, ax' % ('word ptr [bp+%d]' % (2 * i) if i else 'word ptr [bp]'))
    e('mov\tword ptr [bp+64], 10')
    out.append('.Lround:\n')
    for qr in ((0, 4, 8, 12), (1, 5, 9, 13), (2, 6, 10, 14), (3, 7, 11, 15),
               (0, 5, 10, 15), (1, 6, 11, 12), (2, 7, 8, 13), (3, 4, 9, 14)):
        quarter_round(*qr)
    e('dec\tword ptr [bp+64]')
    e('jz\t.Ldone')
    e('jmp\t.Lround')
    out.append('.Ldone:\n')
    e('/* out = x + in, little-endian */')
    e('mov\tsi, [bp+78]\t\t/* in */')
    e('mov\tdi, [bp+76]\t\t/* out */')
    for i in range(16):
        e('mov\tax, %s' % x(i, 0))
        e('mov\tdx, %s' % x(i, 1))
        e('add\tax, [si+%d]' % (4 * i) if i else 'add\tax, [si]')
        e('adc\tdx, [si+%d]' % (4 * i + 2))
        e('mov\t[di+%d], ax' % (4 * i) if i else 'mov\t[di], ax')
        e('mov\t[di+%d], dx' % (4 * i + 2))
    out.append('''\
	add	sp, 66
	pop	bp
	pop	di
	pop	si
	retf
	.size	chacha_block_ia16, .-chacha_block_ia16
''')
    sys.stdout.write(''.join(out))


if __name__ == '__main__':
    main()
