#!/usr/bin/env python3
"""
Generator for src/fe25519_ia16.S -- 8086 assembly for GF(2^255-19) multiply
and square, used by src/curve25519.c on ia16 builds.

    python3 src/fe25519_ia16.py > src/fe25519_ia16.S

The generated file is committed so the ELKS build needs no Python.

Representation (same as uNaCl's MSP430 "mul16" code this is modelled on):
a field element is uint16_t[16], little-endian radix 2^16, holding any
value in [0, 2^256).  It is congruent to the field value mod p = 2^255-19;
full reduction to [0, p) only happens in pack25519().

Algorithm: straight product-scanning (Comba) schoolbook, fully unrolled.
The 512-bit product is built one 16-bit column at a time in a 40-bit
accumulator and each finished column is PUSHed (1 byte, no base register
needed).  Then the high 256 bits are folded into the low 256 bits with
2^256 == 38 (mod p).  The output is always < 2^256.

Why not Karatsuba like uNaCl?  MSP430 has a memory-mapped MAC unit where
accumulation is free.  On the 8088 each product costs one MUL (~120-140
clocks) plus ~12 bytes of instruction fetch at 4 clocks/byte; one-level
Karatsuba saves 64 MULs but adds two 8-limb signed subtractions, a
conditional negate and a 32-word recombination through memory.  That's a
possible follow-up, not a first step.

Calling convention (ia16-elf-gcc, -mcmodel=medium):
  far call, cdecl, args on the stack at [sp+4..] after the far return
  address, caller pops.  Callee must preserve SI, DI, BP (and DS/SS/ES).
  SS == DS, so BP-relative accesses hit the same segment as data pointers.
"""

import sys

NL = 16  # limbs


def emit_header(out):
    out.append("""\
/*
 * fe25519_ia16.S -- GF(2^255-19) multiply and square for 8086/8088.
 *
 * GENERATED by src/fe25519_ia16.py -- edit that, not this.
 *
 * Field elements are uint16_t[16], radix 2^16, value in [0, 2^256),
 * congruent mod 2^255-19.  Outputs are < 2^256; o may alias a or b.
 *
 *   void fe25519_mul(uint16_t o[16], const uint16_t a[16], const uint16_t b[16]);
 *   void fe25519_sq (uint16_t o[16], const uint16_t a[16]);
 *   void fe25519_add(uint16_t o[16], const uint16_t a[16], const uint16_t b[16]);
 *   void fe25519_sub(uint16_t o[16], const uint16_t a[16], const uint16_t b[16]);
 *   void fe25519_mul121665(uint16_t o[16], const uint16_t a[16]);
 *
 * Public domain.  Structure after uNaCl curve25519-msp430 mul16
 * (Hinterwalder, Schwabe et al.), rewritten for 8086.
 */

	.arch	i8086
	.code16
	.intel_syntax noprefix

	/* The trailing $ matters: the ELKS medium-model linker script groups
	 * far code by .fartext.*$ and resolves each function's segment via
	 * the matching .fartext.*! marker.  Without it the code lands in one
	 * far segment while its segment symbol points at another. */
	.section .fartext.fe25519_ia16$,"ax",@progbits
""")


def mem(base, off):
    if off == 0:
        return "[%s]" % base
    return "[%s+%d]" % (base, off)


def gen_mul(out):
    """Product scanning.  Registers during the column loop:
         SI = a, DI = b
         BX = acc bits 0-15, BP = acc bits 16-31, CL = acc bits 32-39
         CH = 0 (so `adc cl,ch` is a 2-byte carry-catch)
       A column holds <= 16 products < 2^32 plus a carry-in < 2^21, so
       40 bits is plenty (CL never exceeds 16).
    """
    out.append("""
	.global	fe25519_mul
	.type	fe25519_mul, @function
fe25519_mul:
	push	si
	push	di
	push	bp
	mov	bp, sp
	mov	si, [bp+12]		/* a */
	mov	di, [bp+14]		/* b */
	xor	bx, bx
	xor	bp, bp
	xor	cx, cx
""")
    for k in range(2 * NL - 1):
        lo = max(0, k - (NL - 1))
        hi = min(k, NL - 1)
        out.append("\t/* column %d */\n" % k)
        for i in range(lo, hi + 1):
            j = k - i
            out.append("\tmov\tax, %s\n" % mem("si", 2 * i))
            out.append("\tmul\tword ptr %s\n" % mem("di", 2 * j))
            out.append("\tadd\tbx, ax\n")
            out.append("\tadc\tbp, dx\n")
            # Column 0 is a single product with zero carry-in; column 30's
            # carry-out is bit 512+ of the product, which is always 0.
            if k != 0 and k != 2 * NL - 2:
                out.append("\tadc\tcl, ch\n")
        out.append("\tpush\tbx\t\t\t/* t[%d] */\n" % k)
        if k != 2 * NL - 2:
            out.append("\tmov\tbx, bp\n")
            out.append("\tmov\tbp, cx\n")
            out.append("\txor\tcl, cl\n")
    out.append("\tpush\tbp\t\t\t/* t[31] */\n")
    out.append("\tjmp\tfe25519_reduce\n")
    out.append("\t.size\tfe25519_mul, .-fe25519_mul\n")


def gen_sq(out):
    """Product scanning with the doubling done per column.  Registers:
         SI = a
         BP = acc bits 0-15, BX = acc bits 16-31, CL = acc bits 32-39
         DI = carry-in bits 0-15, CH = carry-in bits 16-23
       Column k: sum the cross products a[i]*a[j] (i<j, i+j=k) starting
       from zero, double, add a[k/2]^2, then add the carry-in.  Column sums
       are < 2^37 so carries are < 2^21 and fit DI:CH.
    """
    out.append("""
	.global	fe25519_sq
	.type	fe25519_sq, @function
fe25519_sq:
	push	si
	push	di
	push	bp
	mov	bp, sp
	mov	si, [bp+12]		/* a */
	xor	di, di
	xor	cx, cx
""")
    for k in range(2 * NL - 1):
        lo = max(0, k - (NL - 1))
        out.append("\t/* column %d */\n" % k)
        pairs = [(i, k - i) for i in range(lo, NL) if i < k - i]
        first = True
        for (i, j) in pairs:
            out.append("\tmov\tax, %s\n" % mem("si", 2 * i))
            out.append("\tmul\tword ptr %s\n" % mem("si", 2 * j))
            if first:
                out.append("\tmov\tbp, ax\n")
                out.append("\tmov\tbx, dx\n")
                first = False
            else:
                out.append("\tadd\tbp, ax\n")
                out.append("\tadc\tbx, dx\n")
                out.append("\tadc\tcl, 0\n")
        if pairs:
            out.append("\tshl\tbp, 1\n")
            out.append("\trcl\tbx, 1\n")
            out.append("\trcl\tcl, 1\n")
        if k % 2 == 0:
            h = k // 2
            out.append("\tmov\tax, %s\n" % mem("si", 2 * h))
            out.append("\tmul\tax\n")
            if pairs:
                out.append("\tadd\tbp, ax\n")
                out.append("\tadc\tbx, dx\n")
                out.append("\tadc\tcl, 0\n")
            else:
                out.append("\tmov\tbp, ax\n")
                out.append("\tmov\tbx, dx\n")
        if k != 0:
            out.append("\tadd\tbp, di\n")
            out.append("\tadc\tbl, ch\n")
            out.append("\tadc\tbh, 0\n")
            out.append("\tadc\tcl, 0\n")
        out.append("\tpush\tbp\t\t\t/* t[%d] */\n" % k)
        out.append("\tmov\tdi, bx\n")
        if k != 2 * NL - 2:
            out.append("\tmov\tch, cl\n")
            out.append("\txor\tcl, cl\n")
    out.append("\tpush\tdi\t\t\t/* t[31] */\n")
    out.append("\tjmp\tfe25519_reduce\n")
    out.append("\t.size\tfe25519_sq, .-fe25519_sq\n")


def gen_reduce(out):
    """Shared tail.  Stack on entry: t[31] at [sp], t[k] at [sp+2*(31-k)],
    then saved BP, DI, SI, far return address, and the o argument at
    [sp+64+10].

    r = t_lo + 38*t_hi is computed limb by limb with a one-word carry
    (each step is < 38*2^16 + 2^16 + 2^16 < 2^22).  The top carry c is
    <= 38 (t < 2^512 so r < 39*2^256), and 38*c is folded back into
    limb 0 with a full carry chain.  If that chain carries out once more,
    the value left is < 38*38 + 38, so the last +38 lands in limb 0 alone.
    """
    out.append("""
	.type	fe25519_reduce, @function
fe25519_reduce:
	mov	bp, sp
	mov	di, [bp+74]		/* o */
	mov	si, 38
""")
    for i in range(NL):
        t_hi = 2 * (31 - (i + NL))
        t_lo = 2 * (31 - i)
        out.append("\tmov\tax, si\n")
        out.append("\tmul\tword ptr %s\t/* 38 * t[%d] */\n" % (mem("bp", t_hi), i + NL))
        out.append("\tadd\tax, %s\t/* + t[%d] */\n" % (mem("bp", t_lo), i))
        out.append("\tadc\tdx, 0\n")
        if i != 0:
            out.append("\tadd\tax, cx\n")
            out.append("\tadc\tdx, 0\n")
        out.append("\tmov\t%s, ax\n" % mem("di", 2 * i))
        if i != NL - 1:
            out.append("\tmov\tcx, dx\n")
    out.append("\t/* fold top carry (dx <= 38) */\n")
    out.append("\tmov\tax, si\n")
    out.append("\tmul\tdx\n")
    out.append("\tadd\t[di], ax\n")
    for i in range(1, NL):
        out.append("\tadc\tword ptr %s, 0\n" % mem("di", 2 * i))
    out.append("\tsbb\tax, ax\n")
    out.append("\tand\tax, si\n")
    out.append("\tadd\t[di], ax\n")
    out.append("""\
	add	sp, 64
	pop	bp
	pop	di
	pop	si
	retf
	.size	fe25519_reduce, .-fe25519_reduce
""")


def gen_addsub(out, name, op, opc):
    """o = a +/- b mod 2^256, then fold the carry/borrow with 38.

    A second carry/borrow out of the fold chain is only possible when the
    result is within 38 of the wrap point, so the final +/-38 lands in
    limb 0 without further propagation.  Reading a[i], b[i] before writing
    o[i] makes any aliasing safe.
    """
    out.append("""
	.global	%s
	.type	%s, @function
%s:
	push	si
	push	di
	mov	bx, sp
	mov	di, [bx+8]		/* o */
	mov	si, [bx+10]		/* a */
	mov	bx, [bx+12]		/* b */
""" % (name, name, name))
    for i in range(NL):
        out.append("\tmov\tax, %s\n" % mem("si", 2 * i))
        out.append("\t%s\tax, %s\n" % (op if i == 0 else opc, mem("bx", 2 * i)))
        out.append("\tmov\t%s, ax\n" % mem("di", 2 * i))
    out.append("\tsbb\tax, ax\n")
    out.append("\tand\tax, 38\n")
    out.append("\t%s\t[di], ax\n" % op)
    for i in range(1, NL):
        out.append("\t%s\tword ptr %s, 0\n" % (opc, mem("di", 2 * i)))
    out.append("\tsbb\tax, ax\n")
    out.append("\tand\tax, 38\n")
    out.append("\t%s\t[di], ax\n" % op)
    out.append("""\
	pop	di
	pop	si
	retf
	.size	%s, .-%s
""" % (name, name))


def gen_mul121665(out):
    """o = a * 121665 = a * 0xDB41 + (a << 16).

    Limb i: s = a[i]*0xDB41 + a[i-1] + carry < 2^32, carry = s >> 16 fits
    a word.  o[i-1] is written only after a[i-1] and a[i] have been read,
    so o may alias a.  The top word (a[15] + carry) is up to 17 bits;
    38 * top < 2^23 is folded in, and a second carry out of that chain
    leaves a value < 2^23, so the final +38 can carry into limb 1 but no
    further.
    """
    out.append("""
	.global	fe25519_mul121665
	.type	fe25519_mul121665, @function
fe25519_mul121665:
	push	si
	push	di
	mov	bx, sp
	mov	di, [bx+8]		/* o */
	mov	si, [bx+10]		/* a */
	xor	cx, cx
""")
    for i in range(NL):
        out.append("\tmov\tax, 0xdb41\n")
        out.append("\tmul\tword ptr %s\n" % mem("si", 2 * i))
        if i != 0:
            out.append("\tadd\tax, cx\n")
            out.append("\tadc\tdx, 0\n")
            out.append("\tadd\tax, %s\n" % mem("si", 2 * (i - 1)))
            out.append("\tadc\tdx, 0\n")
            out.append("\tmov\t%s, bx\n" % mem("di", 2 * (i - 1)))
        out.append("\tmov\tbx, ax\n")
        out.append("\tmov\tcx, dx\n")
    out.append("""\
	mov	ax, [si+30]
	add	ax, cx			/* top = a[15] + carry, 17 bits */
	mov	[di+30], bx
	sbb	bx, bx
	and	bx, 38
	mov	cx, 38
	mul	cx
	add	dx, bx			/* dx:ax = 38 * top */
	add	[di], ax
	adc	[di+2], dx
""")
    for i in range(2, NL):
        out.append("\tadc\tword ptr %s, 0\n" % mem("di", 2 * i))
    out.append("""\
	sbb	ax, ax
	and	ax, cx
	add	[di], ax
	adc	word ptr [di+2], 0
	pop	di
	pop	si
	retf
	.size	fe25519_mul121665, .-fe25519_mul121665
""")


def main():
    out = []
    emit_header(out)
    gen_mul(out)
    gen_sq(out)
    gen_reduce(out)
    gen_addsub(out, "fe25519_add", "add", "adc")
    gen_addsub(out, "fe25519_sub", "sub", "sbb")
    gen_mul121665(out)
    sys.stdout.write("".join(out))


if __name__ == "__main__":
    main()
