#!/usr/bin/env python3
"""
Generator for src/poly1305_ia16.S -- Poly1305's multiply-and-reduce step
in 8086 assembly, used by src/poly1305_16.c on ia16.

    python3 src/poly1305_ia16.py > src/poly1305_ia16.S

The generated file is committed so the ELKS build needs no Python.

    void poly1305_mulmod_ia16(uint16_t h[10], const uint16_t r[20]);

h = h * r, partially reduced mod 2^130 - 5, exactly as p16_mulmod() in
src/poly1305_16.c (which the host build uses and the tests check).  h and
r are ten 13-bit limbs; r[10..19] holds 5*r for products that wrap past
limb 9.  It must match the C bit for bit, including 32-bit wraparound.

For each output limb i, the C computes a 32-bit sum
    d = c + sum_j h[j] * (j <= i ? r[i-j] : 5*r[i+10-j])
carrying d >> 13 out after j == 4 and again at the end.  Here d lives in
CX:BX, each product is MOV/MUL/ADD/ADC, and d >> 13 is a 35-bit left
shift by 3 into AX:CX (keeping d & 0x1fff in DX first).  Finished limbs
go to a stack buffer and are copied back to h at the end.

Calling convention (ia16-elf-gcc, -mcmodel=medium): far call, cdecl, args
at [sp+4..] after the far return address, caller pops, callee preserves
SI, DI, BP; SS == DS.
"""

import sys

out = []


def e(s):
    out.append('\t' + s + '\n')


def mem(base, off):
    return 'word ptr [%s+%d]' % (base, off) if off else 'word ptr [%s]' % base


# Frame (BP-relative): [0] c_mid lo, [2] c_mid hi, [4..23] limbs d[0..9]
FRAME = 24
CMID = 0
LIMB = 4


def shr13_into_ax_cx():
    """d (CX:BX) -> DX = d & 0x1fff, AX:CX = d >> 13.  Clobbers BX."""
    e('mov\tdx, bx')
    e('and\tdx, 0x1fff')
    e('xor\tax, ax')
    for _ in range(3):
        e('shl\tbx, 1')
        e('rcl\tcx, 1')
        e('rcl\tax, 1')


def main():
    out.append('''\
/*
 * poly1305_ia16.S -- Poly1305 multiply-and-reduce for 8086/8088.
 *
 * GENERATED by src/poly1305_ia16.py -- edit that, not this.
 *
 *   void poly1305_mulmod_ia16(uint16_t h[10], const uint16_t r[20]);
 *
 * Bit-exact with p16_mulmod() in src/poly1305_16.c.
 */

	.arch	i8086
	.code16
	.intel_syntax noprefix

	/* Trailing $ required by ELKS's medium-model linker script; 'x' before
	 * it puts this in the far code segment (see src/chacha_ia16.py). */
	.section .fartext.poly1305_ia16x$,"ax",@progbits

	.global	poly1305_mulmod_ia16
	.type	poly1305_mulmod_ia16, @function
poly1305_mulmod_ia16:
	push	si
	push	di
	push	bp
	sub	sp, %d
	mov	bp, sp
	mov	si, [bp+%d]		/* h */
	mov	di, [bp+%d]		/* r (r[10..19] = 5*r) */
	xor	bx, bx			/* d = c = 0 */
	xor	cx, cx
''' % (FRAME, FRAME + 10, FRAME + 12))
    for i in range(10):
        e('/* limb %d */' % i)
        for j in range(10):
            k = (i - j) if j <= i else (10 + i + 10 - j)
            e('mov\tax, %s' % mem('si', 2 * j))
            e('mul\t%s' % mem('di', 2 * k))
            e('add\tbx, ax')
            e('adc\tcx, dx')
            if j == 4:
                # c_mid = d >> 13; d &= 0x1fff
                shr13_into_ax_cx()
                e('mov\t%s, cx' % mem('bp', CMID))
                e('mov\t%s, ax' % mem('bp', CMID + 2))
                e('mov\tbx, dx')
                e('xor\tcx, cx')
        # c = c_mid + (d >> 13); limb = d & 0x1fff; next d = c
        shr13_into_ax_cx()
        e('add\tcx, %s' % mem('bp', CMID))
        e('adc\tax, %s' % mem('bp', CMID + 2))
        e('mov\t%s, dx' % mem('bp', LIMB + 2 * i))
        e('mov\tbx, cx')
        e('mov\tcx, ax')
    out.append('''\
	/* c (CX:BX) *= 5; c += d[0]; d[0] = c & 0x1fff; d[1] += c >> 13 */
	mov	ax, bx
	mov	dx, cx
	shl	ax, 1
	rcl	dx, 1
	shl	ax, 1
	rcl	dx, 1
	add	ax, bx
	adc	dx, cx
	add	ax, %s
	adc	dx, 0
	mov	bx, ax
	and	bx, 0x1fff
	mov	%s, bx
	shl	ax, 1
	rcl	dx, 1
	shl	ax, 1
	rcl	dx, 1
	shl	ax, 1
	rcl	dx, 1
	add	%s, dx
''' % (mem('bp', LIMB), mem('bp', LIMB), mem('bp', LIMB + 2)))
    e('/* h = d */')
    for i in range(10):
        e('mov\tax, %s' % mem('bp', LIMB + 2 * i))
        e('mov\t%s, ax' % mem('si', 2 * i))
    out.append('''\
	add	sp, %d
	pop	bp
	pop	di
	pop	si
	retf
	.size	poly1305_mulmod_ia16, .-poly1305_mulmod_ia16
''' % FRAME)
    sys.stdout.write(''.join(out))


if __name__ == '__main__':
    main()
